apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  # POSTGRES_PASSWORD_CONFIG: "UGcjMTIz"
  # POSTGRES_USER_CONFIG: "a3ViZW5ld3M="
  # POSTGRES_DB_CONFIG: "a3ViZW5ld3M="
  POSTGRES_PASSWORD: "UGcjMTIz"
  POSTGRES_USER: "a3ViZW5ld3M="
  POSTGRES_DB: "a3ViZW5ld3M="